export default {
    e1: {code: "001", message: "Validation errors were encountered during the process"},
    e2: {code: "002", message: "The data you've selected is already assigned"},
    e3: {code: "003", message: "The information you are looking for is not available"},
    e4: {code: "004", message: "Whoops something went wrong"},
    e5: {code: "005", message: "The provided authentication token is invalid or missing"},
    e6: {code: "006", message: "The token used for authentication is no longer valid"},
    e7: {code: "007", message: "The account status is inactive and requires activation"},
    e8: {code: "008", message: "Password creation failed due to incorrect setup"},
    e9: {code: "009", message: "The system has detected too many incorrect login attempts"},
    e10: {code: "010", message: "Your account has been temporarily locked due to multiple login attempts"},
    e11: {code: "011", message: "The credentials provided do not match our records"},
    e12: {code: "012", message: "The content is read-only and cannot be altered"},
    e13: {code: "013", message: "You do not have the required permissions to access this content"},
    e14: {code: "014", message: "The requested resource could not be located"},
    e15: {code: "015", message: "The data provided does not meet the validation criteria"},
    e16: {code: "016", message: "You must complete OTP verification to access this section"},
    e17: {code: "017", message: "Resending the OTP is currently not possible"},
    e18: {code: "018", message: "There is an issue with your email configuration"},
    e19: {code: "019", message: "There was an issue sending the email"},
    e20: {code: "020", message: "No OTP is necessary for this process"},
    e21: {code: "021", message: "There is an issue with the expiration configuration"},
    e22: {code: "022", message: "The data is no longer valid due to expiration"},
    e23: {code: "023", message: "The OTP provided does not match our records"},
    e24: {code: "024", message: "The system has detected too many incorrect attempts"},
}